name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Debug APK
        run: ./gradlew build

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: debug-apk.apk
          path: app/build/outputs/apk/debug/app-debug.apk


